const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const context = vm.createContext({window:{}});
vm.runInContext(fs.readFileSync('docs/council-meeting-sources.js','utf8'),context);
const records=context.window.BI_COUNCIL_MEETING_SOURCES;
const get=date=>records.find(r=>r.date===date);
assert.match(get('2025-10-21').minutes,/2025-10-21\/council-minutes/);
assert.match(get('2025-09-02').minutes,/2025-09-02\/council-minutes/);
assert.match(get('2020-03-17').minutes,/council-minutes/);
assert.ok(get('2020-03-17').documents.some(d=>d.url.includes('special-meeting-minutes')));
assert.equal(new Set(records.map(r=>r.date)).size,records.length);
assert.equal(context.window.BI_COUNCIL_MINUTES_COMPILATIONS.length,5);
assert.ok(get('2025-10-21').documents.some(d => d.url.includes('2025-11-04/g-2-cc-minutes-10-21-2025')));
assert.ok(get('2025-04-29').documents.some(d => d.url.endsWith('special-meeting-minutes.docx') && d.title.includes('Word original')));
assert.match(get('2022-05-03').minutes, /council-minutes.pdf$/);
assert.ok(get('2022-05-03').documents.some(d => d.url.endsWith('special-meeting-minutes.pdf')));
assert.match(get('2023-04-18').minutes, /council-minutes.pdf$/);
assert.ok(get('2023-04-18').documents.some(d => d.url.endsWith('workshop-minutes.pdf')));
assert.match(get('2023-12-05').minutes, /council-minutes.pdf$/);
assert.ok(get('2023-12-05').documents.some(d => d.url.endsWith('special-meeting-minutes.pdf')));
assert.ok(get('2023-12-07').documents.some(d => d.url.endsWith('workshop-minutes.pdf')));
console.log('Meeting dates, regular/special minutes and annual links passed.');
