"""Build the evidence-led May 7, 2019 interactive council agenda."""
import json
from html import escape as esc
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data/council/2019-05-07-interactive-agenda.json"
OUT = ROOT / "docs/briefings/2019-05-07-sources.html"


def main() -> None:
    data = json.loads(DATA.read_text(encoding="utf-8"))
    groups = []
    for section in ("Closed Session", "Consent", "Public Hearing", "Action", "Reports"):
        rows = []
        for item in (entry for entry in data["items"] if entry["section"] == section):
            seconds = item.get("timestampSeconds")
            video = data["videoUrl"] + (f"&t={seconds}s" if seconds is not None else "")
            watch_label = "Watch from minutes time ↗" if seconds is not None else "Open meeting video ↗"
            tags = " ".join(item.get("tags", []))
            rows.append(f'''<details class="agenda-record" data-section="{esc(section)}"><summary><span class="agenda-number">{esc(item['item'])}</span><span><strong>{esc(item['title'])}</strong><small>{esc(tags)}</small></span></summary><div class="agenda-body"><p><strong>Official outcome:</strong> {esc(item['outcome'])}</p><div class="record-actions"><a class="btn small" href="{esc(video, quote=True)}" target="_blank" rel="noopener">{watch_label}</a><button class="btn small secondary" data-minutes-page="{item['page']}" data-title="May 7, 2019 minutes · page {item['page']}">View minutes page {item['page']}</button></div></div></details>''')
        groups.append(f'<section class="agenda-section"><h2>{esc(section)}</h2>{"".join(rows)}</section>')

    html = f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>May 7, 2019 Interactive Agenda | Beaumont Intelligence</title><link href="../favicon.png" rel="icon"><link href="../styles.css" rel="stylesheet"><style>
.agenda-toolbar{{display:grid;grid-template-columns:1fr 220px;gap:12px;margin:22px 0}}.agenda-toolbar input,.agenda-toolbar select{{width:100%;padding:13px;border:1px solid var(--line);border-radius:10px;font:inherit}}.agenda-section{{margin:28px 0}}.agenda-section>h2{{border-bottom:3px solid var(--blue);padding-bottom:9px}}.agenda-record{{margin:12px 0;border:1px solid var(--line);border-radius:12px;background:#fff;overflow:hidden}}.agenda-record summary{{cursor:pointer;display:grid;grid-template-columns:56px 1fr;gap:14px;padding:16px 18px;color:var(--blue)}}.agenda-record summary small{{display:block;color:var(--muted);font-weight:600;margin-top:4px}}.agenda-number{{font-weight:900;color:var(--red)}}.agenda-body{{border-top:1px solid var(--line);padding:14px 18px 18px}}.record-actions{{display:flex;flex-wrap:wrap;gap:10px}}.source-note{{border-left:5px solid var(--gold);padding:14px 18px;background:#fff8e7;border-radius:8px}}.viewer-dialog{{width:min(1180px,96vw);height:92vh;border:0;border-radius:14px;padding:0}}.viewer-dialog::backdrop{{background:#001b3dcc}}.viewer-dialog header{{height:58px;display:flex;align-items:center;justify-content:space-between;padding:0 16px}}.viewer-dialog iframe{{display:block;width:100%;height:calc(92vh - 58px);border:0}}[hidden]{{display:none!important}}@media(max-width:650px){{.agenda-toolbar{{grid-template-columns:1fr}}}}
</style></head><body><a class="skip-link" href="#main">Skip to content</a><div class="preview-banner"><strong>Archived interactive agenda</strong><span>May 7, 2019 · official minutes and meeting video</span></div><header class="app-header"><div class="wrap header-row"><a class="brand" href="../index.html"><img class="brand-logo" src="../mbf-logo.png" alt=""><span class="brand-copy"><strong><span class="red">BEAUMONT</span> <span class="blue">INTELLIGENCE</span></strong><small>Council Intelligence</small></span></a></div></header><main id="main"><section class="section compact"><div class="wrap narrow"><div class="eyebrow">May 7, 2019</div><h1>Interactive council agenda</h1><p class="lead-copy">Search all 37 recorded agenda matters, review the outcome stated in the adopted minutes, and open the meeting video or the exact minutes page.</p><div class="status-actions"><a class="btn" href="https://www.youtube.com/watch?v=c9LrT--e3iY" target="_blank" rel="noopener">Watch full meeting ↗</a><button class="btn secondary" data-minutes-page="71" data-title="May 7, 2019 minutes · pages 71–80">View official minutes</button><a class="btn secondary" href="../council-meeting-sources.html">Available meeting sources</a></div><p class="source-note"><strong>Transcript status:</strong> YouTube reports that captions and a transcript are unavailable for this video. Timestamp links are therefore limited to times expressly stated in the adopted minutes; other items open the full meeting video. The individual agenda packet has not yet been archived in BI.</p><div class="agenda-toolbar"><input id="agenda-search" type="search" placeholder="Search Urban Logic, wastewater, budget…"><select id="agenda-section"><option value="all">All sections</option><option>Closed Session</option><option>Consent</option><option>Public Hearing</option><option>Action</option><option>Reports</option></select></div><p id="agenda-count" aria-live="polite"></p><div id="agenda-results">{"".join(groups)}</div></div></section></main><dialog class="viewer-dialog" id="viewer-dialog"><header><strong id="viewer-title">Official minutes</strong><button class="btn small" id="viewer-close" type="button">Close ×</button></header><iframe id="viewer-frame" title="Official minutes viewer"></iframe></dialog><script>
(()=>{{const rows=[...document.querySelectorAll('.agenda-record')],sections=[...document.querySelectorAll('.agenda-section')],q=document.querySelector('#agenda-search'),f=document.querySelector('#agenda-section'),count=document.querySelector('#agenda-count'),dialog=document.querySelector('#viewer-dialog'),frame=document.querySelector('#viewer-frame'),title=document.querySelector('#viewer-title'),minutes={json.dumps(data['minutesUrl'])};function render(){{const term=q.value.trim().toLowerCase();rows.forEach(row=>{{row.hidden=(f.value!=='all'&&row.dataset.section!==f.value)||(term&&!row.textContent.toLowerCase().includes(term));if(term&&!row.hidden)row.open=true}});sections.forEach(section=>section.hidden=[...section.querySelectorAll('.agenda-record')].every(row=>row.hidden));count.textContent=`${{rows.filter(row=>!row.hidden).length}} of ${{rows.length}} agenda matters shown`}}document.addEventListener('click',e=>{{const button=e.target.closest('[data-minutes-page]');if(!button)return;title.textContent=button.dataset.title;const source=minutes+'#page='+button.dataset.minutesPage;const back=new URL('2019-05-07-sources.html',location.href).href;frame.src=`../documents/viewer.html?url=${{encodeURIComponent(source)}}&title=${{encodeURIComponent(button.dataset.title)}}&returnUrl=${{encodeURIComponent(back)}}&returnLabel=${{encodeURIComponent('Back to interactive agenda')}}`;dialog.showModal()}});document.querySelector('#viewer-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>frame.src='about:blank');q.addEventListener('input',render);f.addEventListener('change',render);render()}})();
</script></body></html>'''
    OUT.write_text(html, encoding="utf-8", newline="\n")
    print(f"Built {OUT.relative_to(ROOT)} with {len(data['items'])} agenda matters")


if __name__ == "__main__":
    main()
