"""Render the Land Policy center from its reviewed, source-linked timeline."""
import json
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / 'docs'
data = json.loads((ROOT / 'data/land-policy/timeline.json').read_text(encoding='utf-8'))
template = (DOCS / 'downtown-revitalization.html').read_text(encoding='utf-8')
header = template[template.index('<header'):template.index('<div class="project-banner">')]
footer = template[template.index('<footer'):template.index('<script src="data.js">')]
footer = footer.replace('Downtown Revitalization Intelligence Center · Initial Preview', 'Land Policy Intelligence Center · Source-linked history')
pages = [('land-policy', 'Overview'), ('land-policy-history', 'Timeline'), ('land-policy-council-actions', 'Council Actions'), ('land-policy-questions', 'Questions'), ('land-policy-evidence', 'Evidence')]


def links(event):
    labels = [('minutes', 'Official minutes'), ('agenda', 'Interactive agenda'), ('officialAgenda', 'City agenda'), ('transcript', 'Supplied transcript'), ('video', 'Video · ' + event.get('timestamp', '')), ('policy', 'Policy document')]
    return ' · '.join(f'<a href="{escape(event[key], quote=True)}">{escape(label)}</a>' for key, label in labels if event.get(key))


def card(event):
    return f'''<article class="story-card" id="event-{event['date']}"><div class="eyebrow">{event['date']} · {escape(event['item'])}</div><h3>{escape(event['title'])}</h3><p><strong>{escape(event['status'])}</strong></p><p>{escape(event['summary'])}</p><p class="source-note"><strong>Evidence limit:</strong> {escape(event['limit'])}</p><p>{links(event)}</p></article>'''


def section(title, body, alternate=False):
    return f'<section class="section compact{" alt" if alternate else ""}"><div class="wrap"><div class="section-heading"><div><h2>{title}</h2></div></div>{body}</div></section>'


overview = section('From logistics concerns to an adopted policy', '''<div class="status-layout"><article class="status-main"><span class="status-kicker">Policy history</span><h2>How Beaumont established PLUS</h2><p>PLUS means Policy on Land Use and Sensitive Receptors. This center follows the public record behind Beaumont's response to warehouse and logistics development: early mitigation discussions, the September 2022 adoption, clarification of applicability, community-benefit amendments and the March 2025 AB 98 revision.</p><p>Start with the timeline to see what Council discussed, directed and adopted, then open the evidence for each milestone.</p><a class="btn" href="land-policy-history.html">Explore the PLUS timeline →</a></article><aside class="snapshot-card"><h3>Center snapshot</h3><dl><div><dt>Initial adoption</dt><dd>September 6, 2022</dd></div><div><dt>Located policy version</dt><dd>March 4, 2025</dd></div><div><dt>Timeline milestones</dt><dd>8</dd></div><div><dt>Research reviewed</dt><dd>October 10, 2026</dd></div></dl></aside></div>''')
overview += section('What this center tracks', '''<div class="feature-grid"><article class="feature"><h3>Residents and sensitive uses</h3><p>How policy decisions address impacts around homes, schools, parks and other sensitive uses.</p></article><article class="feature"><h3>Development and mitigation</h3><p>How project review, site design, construction and operations connect to Council's land-use decisions.</p></article><article class="feature"><h3>Community benefit</h3><p>When Council directed and adopted fee language, and what remains to be documented about agreements, receipts and spending.</p></article></div>''', True)
overview += section('Key decisions', '<div class="story-grid">' + ''.join(card(data['events'][i]) for i in [2, 5, 7]) + '</div>')
overview += section('Related research', '''<div class="feature-grid"><article class="feature"><h3>Growth and development</h3><p><a href="intelligence-centers.html#growth-community-development">Growth &amp; Community Development</a></p><p><a href="dossiers/billboards.html">Billboards &amp; Sign Policy</a></p></article><article class="feature"><h3>Transportation</h3><p><a href="council-meeting-sources.html">Council meeting source archive</a></p><p><a href="search.html?q=truck%20routes">Search truck-route records</a></p></article><article class="feature"><h3>Public investment</h3><p><a href="budget.html">Budget Center</a></p><p><a href="downtown-revitalization.html">Downtown Revitalization</a></p></article></div>''', True)

history = section('The establishment and evolution of PLUS', '<p>Read chronologically from the early mitigation discussions to the latest policy version located. Committee reports and staff direction are labeled separately from adoption.</p><div class="story-grid">' + ''.join(map(card, data['events'])) + '</div>')
actions = section('Council decision register', '<p>The minutes establish motions and outcomes. The April committee report is included in the timeline as context, rather than as a Council action.</p><div class="story-grid">' + ''.join(card(e) for e in data['events'] if e['status'] != 'Committee report') + '</div>')
questions = section('Questions about PLUS', '''<div class="feature-grid"><article class="feature"><h3>When was PLUS established?</h3><p>September 6, 2022. Council accepted the draft redlines with a setback stipulation and separately voted to name it PLUS. The October 4 clarification identifies September 6 as the adoption date.</p><a href="land-policy-history.html#event-2022-09-06">Read the adoption evidence →</a></article><article class="feature"><h3>Did the early discussions adopt a policy?</h3><p>The January 2022 motion directed DIF study preparation. The April report described committee outreach. PLUS adoption followed in September.</p><a href="land-policy-history.html#event-2022-01-18">Read the early history →</a></article><article class="feature"><h3>When did community-benefit language change?</h3><p>Staff direction in December 2023 preceded adopted amendments in February and May 2024. These actions do not establish actual receipts or expenditures.</p><a href="land-policy-council-actions.html#event-2023-12-19">Review the amendment sequence →</a></article><article class="feature"><h3>What policy document is available?</h3><p>The City Planning page links a PLUS document dated March 4, 2025, the date of Council's AB 98 amendment.</p><a href="land-policy-evidence.html">Open the policy source →</a></article><article class="feature"><h3>Does PLUS replace environmental review?</h3><p>The located policy describes project review alongside CEQA and project-level mitigation.</p><a href="land-policy-evidence.html">Read the policy →</a></article><article class="feature"><h3>Has the policy worked?</h3><p>The adoption record alone cannot answer that. Project conditions, inspection records, complaints, enforcement and measured impacts are needed to evaluate implementation.</p></article></div>''')
policy_url = escape(data['policyUrl'], quote=True)
evidence = section('Policy and primary records', f'''<div class="feature-grid"><article class="feature"><h3>Located PLUS policy · March 4, 2025</h3><p>The six-page policy groups provisions around analysis, construction, siting and design, operations, wayfinding and community engagement. It addresses project conditions and review near sensitive uses.</p><a class="btn" href="documents/viewer.html?url={escape(__import__('urllib.parse', fromlist=['quote']).quote(data['policyUrl'], safe=''), quote=True)}">Read PLUS in the BI viewer →</a><p><a href="{policy_url}">Original City policy PDF</a> · <a href="https://www.beaumontca.gov/87/Planning">City Planning page</a></p><p class="source-note">City Planning link and document date checked October 10, 2026. This is the latest version located, not a complete audit of all subsequent legislation.</p></article><article class="feature"><h3>Evidence standard</h3><p>Official minutes support Council motions and outcomes. Supplied transcripts support the early committee discussion and report. Transcript timestamps are navigation aids; automatic transcription can misidentify names and numbers. Video playback has not been independently checked.</p></article><article class="feature"><h3>What remains to be collected</h3><p>Original 2022 policy and redlines; intermediate policy versions and staff reports; committee agendas and minutes; project-specific compliance records; community-benefit agreements, receipts, balances and expenditures.</p></article></div>''')
evidence += section('Sources by milestone', '<div class="story-grid">' + ''.join(f'<article class="story-card"><div class="eyebrow">{e["date"]} · {escape(e["item"])}</div><h3>{escape(e["title"])}</h3><p>{links(e)}</p><p class="source-note">{escape(e["limit"])}</p></article>' for e in data['events']) + '</div>', True)
contents = [overview, history, actions, questions, evidence]

for (slug, label), body in zip(pages, contents):
    nav = ''.join(f'<a {"aria-current=\"page\" class=\"active\" " if name == slug else ""}href="{name}.html">{text}</a>' for name, text in pages)
    html = f'''<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>Land Policy · {label} | Beaumont Intelligence</title><meta name="description" content="Source-linked history of Beaumont's PLUS policy: establishment, applicability, community-benefit amendments and Council decisions."/><meta name="theme-color" content="#0b3567"/><link rel="icon" href="favicon.png"/><link rel="stylesheet" href="styles.css"/></head>
<body data-page="{slug}"><a class="skip-link" href="#main">Skip to content</a>
{header}<div class="project-banner"><div class="wrap"><nav aria-label="Breadcrumb" class="breadcrumbs"><a href="index.html">Home</a><span aria-hidden="true">›</span><a href="intelligence-centers.html#growth-community-development">Intelligence Centers</a><span aria-hidden="true">›</span><span aria-current="page">Land Policy · {label}</span></nav><div class="project-banner-row"><div><div class="eyebrow light">Growth &amp; Community Development</div><h1>Land Policy Intelligence Center</h1><p>The establishment and evolution of Beaumont's Policy on Land Use and Sensitive Receptors (PLUS).</p></div><aside><strong>From discussion to policy</strong><span>Early 2022 mitigation discussions · September 2022 adoption · 2024 amendments · March 2025 AB 98 revision</span></aside></div><nav aria-label="Land Policy center pages" class="project-nav center-nav">{nav}</nav></div></div>
<main id="main">{body}<section class="section compact"><div class="wrap"><div class="notice"><strong>Research coverage:</strong> This center documents the located historical record. Original policy versions, project compliance and community-benefit accounting remain open research questions. <a href="land-policy-evidence.html">Review sources and evidence gaps →</a></div></div></section></main>
{footer}<script src="data.js"></script><script src="app.js"></script></body></html>
'''
    (DOCS / f'{slug}.html').write_text(html, encoding='utf-8')
print(f'Built {len(pages)} Land Policy center pages from {len(data["events"])} milestones.')
