"""Generate the Center and search records from the existing financial Source Register."""
import json
from html import escape
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / 'docs'
CENTER = 'wrcog-restitution'
register = json.loads((ROOT / 'data/budget/source-register.json').read_text(encoding='utf-8'))
sources = [s for s in register['sources'] if CENTER in s.get('relatedCenters', [])]
ids = [s['sourceId'] for s in register['sources']]
assert len(ids) == len(set(ids)), 'Duplicate Source IDs'

def page(title, body, *, evidence=False):
    active_overview = '' if evidence else ' class="active" aria-current="page"'
    active_evidence = ' class="active" aria-current="page"' if evidence else ''
    current = 'Evidence' if evidence else 'WRCOG &amp; Restitution'
    eyebrow = 'Documentation &amp; Evidence' if evidence else 'Finance &amp; City Government'
    intro = ('Official records supporting the WRCOG settlement, third-party litigation, '
             'restitution, recoveries, and allocation research.' if evidence else
             'Track the WRCOG litigation and settlement, restitution orders and collections, '
             'third-party recoveries, and the amounts ultimately retained by Beaumont.')
    status = ('Sources retain permanent IDs, page references, verification status, and review limits.' if evidence else
              'Settlement approval records are documented. Actual collections and final allocations remain under review.')
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{escape(title)} | Beaumont Intelligence</title><meta name="description" content="Evidence-linked WRCOG settlement, restitution, recovery, and City allocation research."><meta name="theme-color" content="#0b3567"><link rel="stylesheet" href="styles.css"><link rel="icon" href="favicon.png"></head>
<body data-page="{'wrcog-evidence' if evidence else 'wrcog-overview'}"><a class="skip-link" href="#main">Skip to content</a>
<div class="preview-banner"><strong>★ {'Evidence Register' if evidence else 'Public Preview'}</strong><span>Research is expanded as official records are verified and archived.</span></div>
<header class="app-header"><div class="wrap header-row"><a aria-label="Beaumont Intelligence home" class="brand" href="index.html"><img alt="Moving Beaumont Forward logo" class="brand-logo" src="mbf-logo.png"><span class="brand-copy"><strong><span class="red">MOVING</span> <span class="blue">BEAUMONT</span> <span class="red">FORWARD</span></strong><small>WRCOG &amp; Restitution</small><em>Connecting Today's Decisions to Tomorrow's Beaumont.</em></span></a><button aria-controls="primary-nav" aria-expanded="false" class="menu-button" id="menu-button">Menu</button><nav aria-label="Primary navigation" class="primary-nav" id="primary-nav"><a href="index.html">Home</a><a href="council-intelligence.html">Council Intelligence</a><a aria-current="page" href="intelligence-centers.html">Intelligence Centers</a><a href="documents/index.html">Research Library</a><a href="about.html">About</a></nav></div></header>
<div class="project-banner"><div class="wrap"><nav aria-label="Breadcrumb" class="breadcrumbs"><a href="index.html">Home</a><span aria-hidden="true">›</span><a href="intelligence-centers.html">Intelligence Centers</a><span aria-hidden="true">›</span><a href="intelligence-centers.html#finance-government">Finance &amp; City Government</a><span aria-hidden="true">›</span><span aria-current="page">{current}</span></nav><div class="project-banner-row"><div><div class="eyebrow light">{eyebrow}</div><h1>{escape(title)}</h1><p>{escape(intro)}</p></div><aside><strong>{'Evidence first' if evidence else 'Research status'}</strong><span>{escape(status)}</span></aside></div>
<nav aria-label="WRCOG and Restitution center pages" class="project-nav center-nav"><a{active_overview} href="wrcog-restitution.html">Overview</a><a href="wrcog-restitution.html#settlement">Settlement</a><a href="wrcog-restitution.html#financial-tracks">Recoveries</a><a href="wrcog-restitution.html#council-actions">Council Actions</a><a href="wrcog-restitution.html#records-needed">Questions</a><a{active_evidence} href="wrcog-restitution-evidence.html">Evidence</a></nav></div></div>
<main id="main">{body}</main>
<footer class="footer"><div class="wrap footer-grid"><div class="footer-brand"><a aria-label="Beaumont Intelligence home" class="footer-home" href="index.html"><img alt="" src="mbf-logo.png"><div><strong>Moving Beaumont Forward</strong><p>Beaumont Intelligence</p></div></a></div><div><strong>Connecting Today's Decisions to Tomorrow's Beaumont.</strong><p>Official records, historical context, and plain-English civic intelligence.</p></div><div><strong>Quick Links</strong><nav aria-label="Footer navigation" class="footer-nav"><a href="index.html">Home</a><a href="council-intelligence.html">Council Intelligence</a><a href="intelligence-centers.html">Intelligence Centers</a><a href="documents/index.html">Research Library</a><a href="about.html">About</a></nav><p class="footer-version">WRCOG &amp; Restitution Intelligence Center · Public Preview</p></div></div></footer><script src="data.js"></script><script src="app.js"></script></body></html>'''

overview = f'''<section class="section compact"><div class="wrap"><div class="status-layout"><article class="status-main"><span class="status-kicker">Research status</span><h2>Settlement terms and Council actions are documented; collections remain under review.</h2><p>The Center now connects the WRCOG litigation, settlement provisions, third-party claims, restitution research, and later litigation records without treating an order or authorization as money received.</p><div class="status-actions"><a class="btn" href="wrcog-restitution-evidence.html">Review the evidence →</a><a class="btn ghost" href="#financial-tracks">Understand the recovery tracks →</a></div></article><aside class="snapshot-card"><h3>Center Snapshot</h3><dl><div><dt>Registered sources</dt><dd>{len(sources)}</dd></div><div><dt>Settlement record</dt><dd>Approval copies</dd></div><div><dt>Actual collections</dt><dd>Under review</dd></div><div><dt>Evidence system</dt><dd>Shared Source Register</dd></div></dl></aside></div></div></section>
<section class="section compact alt"><div class="wrap"><div class="section-heading"><div><div class="eyebrow">Explore the record</div><h2>Five connected research paths</h2></div><p>Start with the subject you need, then move directly to the supporting evidence.</p></div><div class="story-grid"><article class="story-card"><span>1</span><h3>Judgment &amp; Settlement</h3><p>Review the approval-copy terms that resolved the WRCOG litigation and established recovery-sharing provisions.</p><a href="#settlement">Review settlement terms →</a></article><article class="story-card"><span>2</span><h3>Restitution &amp; Recoveries</h3><p>Keep court orders, payments received, civil recoveries, insurance proceeds, and net City proceeds separate.</p><a href="#financial-tracks">Compare recovery tracks →</a></article><article class="story-card"><span>3</span><h3>Third-Party Claims</h3><p>Follow tolling agreements and litigation involving auditors, attorneys, a bond trustee, Urban Logic, and insurers.</p><a href="#third-party-claim-preservation">Trace the claims →</a></article><article class="story-card"><span>4</span><h3>Council Actions</h3><p>Review documented settlement, membership, TUMF, litigation, and claims-preservation actions by meeting date.</p><a href="#council-actions">View the timeline →</a></article><article class="story-card"><span>5</span><h3>Source Register</h3><p>Open permanent evidence records with verification status, page references, summaries, and review limitations.</p><a href="wrcog-restitution-evidence.html">Browse all sources →</a></article></div></div></section>
<section class="section compact"><div class="wrap"><div class="section-heading"><div><div class="eyebrow">About this center</div><h2>Documenting what was ordered, recovered, and retained</h2></div><p>The evidence layer supporting My Story and independent public review.</p></div><p>This Center documents the WRCOG litigation and settlement, criminal restitution, and other recoveries involving the City of Beaumont. It is the documentary research layer that My Story can cite.</p>
<div class="notice"><strong>Settlement approval text reviewed; collections unverified.</strong> The May 16, 2017 packet documents the proposed amended agreement terms, and the minutes document Council approval. A fully executed agreement and records of actual receipts remain needed. An empty ledger means records have not been loaded; it does not mean no money was recovered.</div></div></section>
<section class="section compact alt" id="financial-tracks"><div class="wrap"><div class="section-heading"><div><div class="eyebrow">Recovery framework</div><h2>Keep the financial tracks separate</h2></div></div><ol>
<li>WRCOG judgment and settlement: exposure and the terms resolving it.</li>
<li>Criminal restitution orders: amounts a court ordered.</li>
<li>Restitution collected: documented payments actually received.</li>
<li>Civil litigation recoveries: separately documented civil settlements.</li>
<li>Insurance and professional-liability settlements.</li>
<li>Other recoveries or reimbursements, including separately classified loan repayments.</li>
<li>WRCOG’s contractual share of qualifying recoveries.</li>
<li>Beaumont’s net recovery after documented allocations and costs.</li></ol>
<p><strong>Ordered does not mean paid. Gross recovery does not mean Beaumont’s net recovery.</strong> An unknown amount will remain unknown, never silently become zero.</p></div></section>
<section class="section compact" id="records-needed"><div class="wrap"><div class="feature-grid"><article class="feature"><h3>Records still needed</h3><p>The fully executed amended settlement, referenced exhibits and dismissal records; audited financial statements; sentencing and restitution orders; payment and receipt records; third-party settlement agreements; allocation and legal-cost schedules.</p></article><article class="feature"><h3>My Story evidence links</h3><p>Chapters can link to permanent Source IDs, recoveries, people, organizations, cases, and timeline events. Narrative recollections remain separate from contemporary records.</p><a class="text-link" href="wrcog-restitution-evidence.html">View evidence →</a></article><article class="feature"><h3>Related personnel records</h3><p>Kapanicas employment and CalPERS records remain a separate evidence request and are not classified as restitution or recovery.</p></article><article class="feature"><h3>Evidence standards</h3><p>Allegations, charges, convictions, settlements, orders, receipts, and allocations remain distinct. Confidential discussions are not inferred.</p></article></div></div></section>'''
milestones = json.loads((ROOT / 'data/council/2017-minutes-intake.json').read_text(encoding='utf-8'))
timeline = ''.join(f'<li><strong>{escape(event["date"])}</strong> — {escape(event["finding"])} <a href="wrcog-restitution-evidence.html#{milestones["sourceIds"][0]}">Minutes, PDF page {event["pdfPage"]}</a></li>' for event in milestones['findings'])
overview += f'<section class="section compact alt" id="council-actions"><div class="wrap"><div class="section-heading"><div><div class="eyebrow">Decision history</div><h2>Documented Council actions</h2></div><p>Approval does not itself establish execution, dismissal, or payment.</p></div><ol>{timeline}</ol><p><a class="text-link" href="council-meeting-sources.html">Browse Council videos, agendas and minutes →</a></p></div></section>'
precursor_actions = [
    ('May 3, 2016', 'Council records place a tolling agreement with former City auditor Moss Levy & Hartzheim on the consent calendar; the minutes record approval.', 'SRC-0041'),
    ('May 17, 2016', 'The closed-session report records a unanimous vote to deny a claim submitted by Urban Logic Consultants.', 'SRC-0047'),
    ('June 21, 2016', 'Council records place tolling agreements with Norton Rose Fulbright, MUFG Union Bank, and McFarlin & Anderson on the consent calendar; the minutes record approval.', 'SRC-0042'),
]
precursor_timeline = ''.join(
    f'<li><strong>{escape(date)}</strong> — {escape(finding)} <a href="wrcog-restitution-evidence.html#{source_id}">View evidence</a></li>'
    for date, finding, source_id in precursor_actions
)
overview += f'<section class="section compact" id="third-party-claim-preservation"><div class="wrap"><div class="section-heading"><div><div class="eyebrow">Claims history</div><h2>Third-party claim preservation</h2></div></div><p>These 2016 records show steps taken to preserve potential claims while the WRCOG litigation remained pending. A tolling agreement is not proof of liability, a later settlement, money received, or a WRCOG allocation.</p><ol>{precursor_timeline}</ol><div class="notice" id="urban-logic-appeal"><strong>May 18, 2021 · Later Urban Logic litigation:</strong> Council minutes record unanimous authorization for a written appeal in City of Beaumont v. Urban Logic Consultants, Inc. et al. Filing, disposition, recovery, and allocation require separate records. <a href="wrcog-restitution-evidence.html#SRC-0046">View evidence →</a></div></div></section>'
terms = json.loads((ROOT / 'data/wrcog-restitution/settlement-terms.json').read_text(encoding='utf-8'))
source_link = f'wrcog-restitution-evidence.html#{terms["sourceId"]}'
rows = ''.join(f'<tr><th scope="row">{escape(t["range"])}</th><td>{t["wrcogPercent"]}%</td><td>{t["beaumontPercent"]}%</td></tr>' for t in terms['allocation']['tiers'])
findings = ''.join(f'<article class="feature"><h3>{escape(f["title"])}</h3><p>{escape(f["text"])}</p><p><small>Packet pages {escape(f["packetPages"])}; Item 3 extract pages {escape(f["extractPages"])}</small></p></article>' for f in terms['findings'])
overview += f'<section class="section compact alt" id="settlement"><div class="wrap"><div class="section-heading"><div><div class="eyebrow">Settlement terms</div><h2>May 2017 settlement approval copy</h2></div><p><a class="text-link" href="{source_link}">View source and approval-copy limitations →</a></p></div><p>The unsigned clean agreement appears after the comparison version in Item 3.</p><h3>Third Party Claim recovery shares</h3><p>Section 1.3.5; packet page 164, extract page 20. These brackets apply to qualifying recoveries, not the entire amount at a single rate. No actual distribution is calculated here.</p><table><thead><tr><th>Recovery bracket</th><th>WRCOG</th><th>Beaumont</th></tr></thead><tbody>{rows}</tbody></table><div class="feature-grid">{findings}</div><p><a class="text-link" href="wrcog-restitution-evidence.html#{terms["originalAgreementSourceId"]}">View the original April agreement and exhibits →</a></p></div></section>'
cards = []
search = [{'title': 'WRCOG & Restitution Intelligence Center', 'url': CENTER + '.html', 'category': 'Intelligence Center', 'description': 'Settlement approval-copy terms and documented Council actions; actual collections and allocations remain unverified.', 'text': 'WRCOG restitution Urban Logic Beaumont recoveries My Story evidence CalPERS', 'aliases': []}]
for s in sources:
    sid = s['sourceId']
    url = s.get('archivePath') or s.get('officialUrl')
    target = url if url and 'portal.laserfiche.com/' in url else f'documents/viewer.html?url={quote(url or "", safe="")}'
    link = f'<a class="text-link" href="{escape(target, quote=True)}">Open source document →</a>' if url else '<p>Document not yet available.</p>'
    link += ''.join(f' <a class="text-link" href="{escape(path, quote=True)}">Related evidence record →</a>' for path in s.get('crossLinks', []))
    page_refs = ', '.join(s.get('pageReferences', []))
    citation = f'<p>Page reference: {escape(page_refs)}</p>' if page_refs else ''
    limitations = f'<p><strong>Review notes:</strong> {escape(s.get("notes") or "")}</p>' if s.get('notes') else ''
    cards.append(f'<article class="story-card" id="{escape(sid)}"><span>{escape(sid)}</span><h3>{escape(s["title"])}</h3><p><strong>{escape(s["verificationStatus"])}</strong> · {escape(s.get("publisher", ""))}</p><p>{escape(s.get("summary", ""))}</p>{citation}{limitations}{link}</article>')
    search.append({'title': s['title'], 'url': CENTER + '-evidence.html#' + sid, 'category': 'Source Document', 'description': s.get('summary', ''), 'text': f'{sid} {s["verificationStatus"]} WRCOG restitution', 'aliases': []})
evidence = '<section class="section compact"><div class="wrap"><div class="section-heading"><div><div class="eyebrow">Shared Source Register</div><h2>Verified records and review limits</h2></div><p>Permanent SRC identifiers connect this Center to the existing financial evidence system.</p></div><div class="story-grid">' + (''.join(cards) or '<article class="story-card"><span>Pending</span><h3>No sources registered</h3><p>Documents will appear after registration and review.</p></article>') + '</div><p><a class="text-link" href="budget-evidence.html">Browse existing financial evidence →</a></p></div></section>'
(DOCS / (CENTER + '.html')).write_text(page('WRCOG & Restitution Intelligence Center', overview), encoding='utf-8')
(DOCS / (CENTER + '-evidence.html')).write_text(page('WRCOG & Restitution Evidence Explorer', evidence, evidence=True), encoding='utf-8')
search.append({'title': 'WRCOG settlement and membership Council actions', 'url': 'wrcog-restitution.html#council-actions', 'category': 'Timeline Event', 'description': '2017 settlement approval, WRCOG membership and TUMF actions documented in Council minutes.', 'text': 'April 4 May 16 June 20 July 18 September 5 2017 WRCOG', 'aliases': []})
search.append({'title': '2016 third-party claim-preservation actions', 'url': 'wrcog-restitution.html#third-party-claim-preservation', 'category': 'Timeline Event', 'description': 'Council records for tolling agreements involving Moss Levy & Hartzheim, Norton Rose Fulbright, MUFG Union Bank, and McFarlin & Anderson.', 'text': 'May 3 June 21 2016 tolling agreement auditor bond counsel trustee professional liability', 'aliases': []})
search.append({'title': 'Urban Logic appeal authorization', 'url': 'wrcog-restitution.html#urban-logic-appeal', 'category': 'Timeline Event', 'description': 'May 18, 2021 Council authorization for a written appeal in the City of Beaumont v. Urban Logic litigation.', 'text': 'May 18 2021 Urban Logic RIC 1707201 RIC1712042 appeal authorization', 'aliases': []})
search.append({'title': 'WRCOG & Restitution Source Register', 'url': CENTER + '-evidence.html', 'category': 'Intelligence Center', 'description': 'Shared financial Source Register with Council records and settlement approval materials.', 'text': 'WRCOG restitution source documents evidence My Story', 'aliases': []})
search.append({'title': 'November 3, 2015 Interactive Council Agenda', 'url': 'briefings/2015-11-03-sources.html', 'category': 'Council Intelligence', 'description': 'Official agenda, supporting records and meeting video. Outcomes and timestamps pending.', 'text': 'WRCOG RIC 536164 Urban Futures financial report quiet zones Interwest wastewater fire IT services climate plan', 'aliases': []})
(DOCS / 'evidence-search-index.js').write_text('window.BI_EVIDENCE_SEARCH_INDEX=' + json.dumps(search, ensure_ascii=False) + ';\n', encoding='utf-8')
print(f'Built WRCOG shell with {len(sources)} registered sources.')
